version: "3.8"

services:
  # Application Next.js + Backend
  app:
    build: ./frontend
    container_name: goalcraft-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:${MONGO_PASSWORD:-goalcraft2024}@mongodb:27017/goalcraft?authSource=admin
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-change-this-in-production}
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # Encryption pour les conversations
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # n8n Webhook
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://n8n:5678/webhook}
      - N8N_API_KEY=${N8N_API_KEY:-}
      # URLs publiques
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - SERVER_URL=${SERVER_URL:-http://localhost:3000}
    depends_on:
      - mongodb
      - n8n
    restart: unless-stopped
    networks:
      - goalcraft-network

  # MongoDB
  mongodb:
    image: mongo:7
    container_name: goalcraft-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-goalcraft2024}
      - MONGO_INITDB_DATABASE=goalcraft
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped
    networks:
      - goalcraft-network

  # n8n pour les workflows IA
  n8n:
    image: n8nio/n8n:latest
    container_name: goalcraft-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-goalcraft2024}
      - N8N_EXECUTION_TIMEOUT=300
      - N8N_EXECUTION_TIMEOUT_MAX=600
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows
    restart: unless-stopped
    networks:
      - goalcraft-network

volumes:
  mongodb_data:
    driver: local
  n8n_data:
    driver: local

networks:
  goalcraft-network:
    driver: bridge
